version: '3'

services:
  redis:
    image: 'redis:latest'
    container_name: 'my-redis-container-two'
    ports:
      - '6379:6379'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
