version: '3'

services:
  node-app:
    container_name: my-node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
